"""user_id_in_tasks

Revision ID: c50055cd47e1
Revises: bd8e8705616f
Create Date: 2025-08-18 23:22:48.874159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c50055cd47e1'
down_revision: Union[str, Sequence[str], None] = 'bd8e8705616f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tasks_table', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Tasks_table', 'UserProfile', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Tasks_table', type_='foreignkey')
    op.drop_column('Tasks_table', 'user_id')
    # ### end Alembic commands ###
