"""yandex-access-token-new

Revision ID: dfcf39a3094c
Revises: 094c00e6bb6a
Create Date: 2025-08-21 16:11:35.797403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfcf39a3094c'
down_revision: Union[str, Sequence[str], None] = '094c00e6bb6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('UserProfile_yandex_access_token_key'), 'UserProfile', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('UserProfile_yandex_access_token_key'), 'UserProfile', ['yandex_access_token'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
